# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
import numpy as np

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color_dtype=np.dtype([
    ("red",'uint8'),
    ("green",'uint8'),
    ("blue",'uint8'),
    ("alpha",'uint8')
])
first_color=np.array([(50,100,40,30),(30,120,70,47)],dtype=color_dtype)
print(first_color)
print(first_color.dtype)

[(50, 100, 40, 30) (30, 120, 70, 47)]
[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
arr1=np.random.randint(1,50,size=(5,3))
arr2=np.random.randint(1,50,size=(3,2))
print(arr1)
print("--------------------------")
print(arr2)
print("--------------------------")
product=np.dot(arr1,arr2)
print(product)

[[20 23 48]
 [42  3 46]
 [37 24 36]
 [16 41  1]
 [45 48 41]]
--------------------------
[[19 37]
 [28  5]
 [43  9]]
--------------------------
[[3088 1287]
 [2860 1983]
 [2923 1813]
 [1495  806]
 [3962 2274]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
np.random.seed(10)
arr1=np.random.randint(1,10,10)
print(arr1)
print("--------------------------")
for i in range(arr1.shape[0]):
  num=arr1[i]
  if(num>3 and num < 8):
    arr1[i]=-num
print(arr1)

[5 1 2 1 2 9 1 9 7 5]
--------------------------
[-5  1  2  1  2  9  1  9 -7 -5]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

Answer:
the output will 9 because first the range function was called to number 5
exclusive and we sum the number from 1 to 4 then in last we subtract 1 one from the result





In [ ]:
print(sum(range(5),-5))

5


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z is legal like if z=[1,2,3] then z**z will be [1,4,27]
2<<z>>z is legal bitwise shift we will shift bits two to the left 2<<z and then two to the right z>>2
z<-z is illegal
if 1j is imaginary number then its totally legal to use complex number in numpy
z<z>z is illegal it should chaind like z<z or z>z may work not shure if its will work for the full array i think it should be compared element by element

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0)) #the result will be nan because we are dividing by zero
print(np.array([np.nan]).astype(int).astype(float))#will print the min number int

nan
[-9.22337204e+18]


/tmp/ipython-input-22-2861855394.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) #the result will be nan because we are dividing by zero
/tmp/ipython-input-22-2861855394.py:2: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr=np.array([1.6,-0.4,1.4,-1.2])
for i in range(arr.shape[0]):
  num=arr[i]
  if num <0:
    arr[i]=np.floor(num)
  else:
    arr[i]=np.ceil(num)
print(arr)

[ 2. -1.  2. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1=np.array(range(1,7))
arr2=np.array(range(4,10))
print(np.intersect1d(arr1,arr2))

[4 5 6]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
the answer is false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today=np.datetime64('today','D')
print("today is: ",today)
yesterday=today-1
print("yesterday was:",yesterday)
tomorrow=today+1
print("tomorrow:",tomorrow)

today is:  2025-07-23
yesterday was: 2025-07-22
tomorrow: 2025-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
np.random.seed(10)
a=np.random.randint(10,size=5)
b=np.random.randint(10,size=5)
a=a.astype(np.float16)
b=b.astype(np.float16)
print(a,b)
x=np.negative(a)
np.add(a,b,out=a)
np.divide(x,2.0,out=x)
np.multiply(a,x,out=a)
print(a)

[9. 4. 0. 1. 9.] [0. 1. 8. 9. 0.]
[-40.5 -10.   -0.   -5.  -40.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
#method 1
arr=np.array([2.1,5,6.7,1.5,10,7.5])
arr=arr.astype(np.int16)
print(arr)
#method 2
arr2=np.array([2.1,5,6.7,1.5,10,7.5],dtype="i8")
print(arr2)
#method 3
arr3=np.array([2.1,5,6.7,1.5,10,7.5])
print(np.floor(arr3))
#method 4
arr4=np.array([2.1,5,6.7,1.5,10,7.5])
frac_part,decimal_part=np.modf(arr4)
print(decimal_part)

[ 2  5  6  1 10  7]
[ 2  5  6  1 10  7]
[ 2.  5.  6.  1. 10.  7.]
[ 2.  5.  6.  1. 10.  7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.full((5,5),range(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def genarator10():
  return np.random.randint(1000,size=10)
arr=genarator10()
print(arr)

[131 496 690  31 812  67 204 878 399 134]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.random.rand(10)

array([0.73877265, 0.07724832, 0.22312753, 0.44261051, 0.65009726,
       0.36404605, 0.33149094, 0.95152249, 0.24716346, 0.46213289])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
np.sort(np.random.rand(10))

array([0.00284513, 0.30213001, 0.3604674 , 0.36137748, 0.47413814,
       0.50232294, 0.51719393, 0.63168899, 0.83192349, 0.94326603])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:

arr=np.array([2.1,5,6.7,1.5,10,7.5])
arr2=sum(arr)
print(arr2)

32.8


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
def are_equal(arr1,arr2):
  x=(arr1==arr2)
  for i in x:
    if(not i):
      return False
  return True
arr1=np.array([1,2,3,4,7])
arr2=np.array([1,2,3,4,5])
print(are_equal(arr1,arr2))



False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr=np.array(range(10))
arr.setflags(write=False)
print(arr)
arr[0]=10
print(arr)

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
np.random.seed(10)
arr=np.random.randint(10,size=(10,2))
arr=arr.astype(np.float16)
squaring=arr**2
r=np.sqrt(np.sum(squaring,axis=1))
x,y=np.split(arr,2,axis=1)
x=np.copy(x)
theta=np.arctan(y,x)
theta=theta.T
print("in cartisian form :")
print(arr)
print("--------------")
print("in polar form:")
print(r)
print(theta)

in cartisian form :
[[9. 4.]
 [0. 1.]
 [9. 0.]
 [1. 8.]
 [9. 0.]
 [8. 6.]
 [4. 3.]
 [0. 4.]
 [6. 8.]
 [1. 8.]]
--------------
in polar form:
[ 9.85  1.    9.    8.06  9.   10.    5.    4.   10.    8.06]
[[1.326 0.785 0.    1.446 0.    1.405 1.249 1.326 1.446 1.446]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
np.random.seed(9)
arr=np.random.randint(50,size=10)
i=arr.argmax()
print(arr)
print("--------------")
arr[i]=0
print(arr)

[28 22  1 22 40 49 27 33 29 28]
--------------
[28 22  1 22 40  0 27 33 29 28]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
my_type=np.dtype([("x","float16"),("y","float16")])
arr=np.array([(0,0),(0,1),(1,0),(1,1)],dtype=my_type)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

cauchy_mat=np.zeros((x.size,y.size))
for i in range(x.size):
  for j in range(y.size):
    if(x[i]==y[j]):
      print("its dividing by zero exiting")
      break
    cauchy_mat[i][j]=1/(x[i]-y[j])
print(cauchy_mat)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype_name in ['int8', 'int16', 'int32', 'int64', 'uint8', 'uint16', 'uint32', 'uint64']:
    try:
        info = np.iinfo(dtype_name)
        print(f"{dtype_name}: Min = {info.min}, Max = {info.max}")
    except ValueError:
        print(f"Could not get info for {dtype_name}")
for dtype_name in ['float16', 'float32', 'float64', 'float128']:
    try:
        info = np.finfo(dtype_name)
        print(f"{dtype_name}: Min = {info.min}, Max = {info.max}, Epsilon = {info.eps}")
    except ValueError:
        print(f"Could not get info for {dtype_name}")

int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807
uint8: Min = 0, Max = 255
uint16: Min = 0, Max = 65535
uint32: Min = 0, Max = 4294967295
uint64: Min = 0, Max = 18446744073709551615
float16: Min = -65504.0, Max = 65504.0, Epsilon = 0.0009765625
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38, Epsilon = 1.1920928955078125e-07
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308, Epsilon = 2.220446049250313e-16
float128: Min = -inf, Max = inf, Epsilon = 1.0842021724855044e-19


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr=np.arange(1000)
for a in arr:
  print(a)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
np.random.seed(10)
arr=np.random.randint(30,size=10)
print(arr)
target_num=int(input("enter the number you want to target: "))
difference=np.abs(arr-target_num)
i=difference.argmin()
print(f"the nearest value to {target_num} is at index {i} and the value is {arr[i]}")

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
my_dtype=np.dtype([("x","i1"),
                    ("y","i1"),
                    ("color",[("r","i2"),("g","i2"),("b","i2")])])
arr=np.array([(10,2,(125,97,37)),(2,5,(25,143,200))],dtype=my_dtype)
print(arr)

[(10, 2, (125,  97,  37)) ( 2, 5, ( 25, 143, 200))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(100,2))
final_arr=np.zeros((arr.shape[0],arr.shape[0]))

for i in range(arr.shape[0]):
  dist=0
  for j in range(arr.shape[0]):
    diff=arr[i]-arr[j]
    final_arr[i][j]=np.sqrt(np.sum(diff**2))
print(final_arr)

[[ 0.         10.63014581 10.63014581 ...  7.07106781  7.21110255
   9.05538514]
 [10.63014581  0.          0.         ...  7.          3.60555128
   6.08276253]
 [10.63014581  0.          0.         ...  7.          3.60555128
   6.08276253]
 ...
 [ 7.07106781  7.          7.         ...  0.          5.83095189
  10.        ]
 [ 7.21110255  3.60555128  3.60555128 ...  5.83095189  0.
   4.24264069]
 [ 9.05538514  6.08276253  6.08276253 ... 10.          4.24264069
   0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
arr=np.array([1.5,7,8.9,1.3],dtype="float32")
arr=arr.astype(np.int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
np.genfromtxt("filename.csv", delimiter=",")


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
arr=np.random.randint(10,size=(3,3))
for index,value in np.ndenumerate(arr):
  print(index,value)

(0, 0) 3
(0, 1) 9
(0, 2) 7
(1, 0) 9
(1, 1) 9
(1, 2) 7
(2, 0) 0
(2, 1) 0
(2, 2) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:


np.random.seed(11)
arr = np.random.rand(5, 5)

mean = arr.mean()
std = arr.std()

gaussian_like = (1 / (std * np.sqrt(2 * np.pi))) * np.exp(-((arr - mean)**2) / (2 * std**2))
gaussian_like

array([[0.91390624, 0.51570072, 1.29068521, 0.83797199, 1.29315645],
       [1.27960544, 0.5005937 , 1.27832343, 0.33901726, 0.52646167],
       [0.82518719, 0.73276108, 0.43207019, 0.51196842, 0.87598502],
       [1.06034024, 0.51799423, 0.75310735, 1.19882548, 0.85789244],
       [0.75124195, 0.60321352, 1.23764422, 1.20251523, 0.74019286]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(4,4))
print(arr)
numm_p=int(input("enter number of elements you want to replace: "))
random_indices = np.random.choice(arr.size, size=numm_p, replace=False)
print(random_indices)

row_indices, col_indices = np.unravel_index(random_indices, arr.shape)
print(row_indices,col_indices)
arr[row_indices, col_indices] = np.random.randint(15)
arr

[[9 0 1 7]
 [1 7 2 8]
 [0 0 4 2]
 [1 5 5 7]]
enter number of elements you want to replace: 5
[ 5  7 15 10  0]
[1 1 3 2 0] [1 3 3 2 0]


array([[11,  0,  1,  7],
       [ 1, 11,  2, 11],
       [ 0,  0, 11,  2],
       [ 1,  5,  5, 11]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
np.random.seed(20)
arr=np.random.randint(100,size=(10,10))
print("the original array: ","\n",arr)
Avg=arr.mean(axis=0)
arr=arr-Avg
print("the mean of each row: ","\n",Avg)
print("the array after subtracting the mean : ","\n",Avg)

the original array:  
 [[99 90 15 95 28 90  9 20 75 22]
 [71 34 96 40 85 90 26 83 16 62]
 [16  7 98  6 26 13 75 58 25  3]
 [74 75 61 77 83 57 94 32 10  6]
 [75 18  3 77 17 43 16 18 79 90]
 [59 71 75 29 45  6 63 78 24 18]
 [93 33 78 42 94  3 18 70 52 22]
 [14  4 27 75  8  6 26 79 82 78]
 [10 33 85 17 40 82 42 60 84 30]
 [36  8 48 19 48 95 53 10 38  9]]
the mean of each row:  
 [54.7 37.3 58.6 47.7 47.4 48.5 42.2 50.8 48.5 34. ]
the array after subtracting the mean :  
 [54.7 37.3 58.6 47.7 47.4 48.5 42.2 50.8 48.5 34. ]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
np.random.seed(20)
arr=np.random.randint(100,size=(10,10))
print(arr)
i=int(input("enter the coulmn you want to sort based on 0-9"))
sorted_index=arr[:,i].argsort()
arr=arr[sorted_index]
print(arr)

[[99 90 15 95 28 90  9 20 75 22]
 [71 34 96 40 85 90 26 83 16 62]
 [16  7 98  6 26 13 75 58 25  3]
 [74 75 61 77 83 57 94 32 10  6]
 [75 18  3 77 17 43 16 18 79 90]
 [59 71 75 29 45  6 63 78 24 18]
 [93 33 78 42 94  3 18 70 52 22]
 [14  4 27 75  8  6 26 79 82 78]
 [10 33 85 17 40 82 42 60 84 30]
 [36  8 48 19 48 95 53 10 38  9]]
enter the coulmn you want to sort based on 0-95
[[93 33 78 42 94  3 18 70 52 22]
 [59 71 75 29 45  6 63 78 24 18]
 [14  4 27 75  8  6 26 79 82 78]
 [16  7 98  6 26 13 75 58 25  3]
 [75 18  3 77 17 43 16 18 79 90]
 [74 75 61 77 83 57 94 32 10  6]
 [10 33 85 17 40 82 42 60 84 30]
 [99 90 15 95 28 90  9 20 75 22]
 [71 34 96 40 85 90 26 83 16 62]
 [36  8 48 19 48 95 53 10 38  9]]


\#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
arr_nan = np.array([[1.0, np.nan, 3.0],
                    [4.0, np.nan, 6.0],
                    [7.0, np.nan, 9.0]])
check_null=np.any(np.isnan(arr_nan),axis=0)
print(check_null)

[False  True False]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
np.random.seed(10)
arr=np.random.randint(30,size=10)
print(arr)
target_num=int(input("enter the number you want to target: "))
difference=np.abs(arr-target_num)
i=difference.argmin()
print(f"the nearest value to {target_num} is at index {i} and the value is {arr[i]}")

[ 9 29  4 15  0 17 27 28 25 29]
enter the number you want to target: 20
the nearest value to 20 is at index 5 and the value is 17


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
np.random.seed(10)
arr1=np.random.randint(10,size=(1,3))
arr2=np.random.randint(10,size=(3,1))
sum=0
print(arr1)
print(arr2)
for i in range(arr1.shape[1]):
  sum+=arr1[0][i]+arr2[i][0]
print(sum)

[[9 4 0]]
[[1]
 [9]
 [0]]
23


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
my_dtype=np.dtype([("name","U30")])
arr=np.array(["mohamed","ahmed"],dtype=my_dtype)
print(arr)

[('mohamed',) ('ahmed',)]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
np.random.seed(10)
arr1=np.random.randint(10,size=5)
arr2=np.random.choice([0,1,2,3,4],5)
print(arr1,arr2)
for i in arr2:
  arr1[i]=arr1[i]+1
print(arr1)

[9 4 0 1 9] [0 1 2 0 1]
[11  6  1  1  9]


In [ ]:
#other method
np.random.seed(10)
arr1=np.random.randint(10,size=5)
arr2=np.random.choice([0,1,2,3,4],5)
np.add.at(arr1,arr2,1)
arr1

array([11,  6,  1,  1,  9])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
np.random.seed(11)
F=np.random.randint(10,size=8)
X=np.random.randint(10,size=3)
print(F)
print("the indices that i want to accumlate in:",i)
print("the value to accumalte:",X)
i=np.random.choice(range(F.size),size=3)
np.add.at(F,i,X)
print("final array:",F)


[9 0 1 7 1 7 2 8]
the indices that i want to accumlate in: [2 4 1]
the value to accumalte: [0 0 4]
final array: [9 4 1 7 1 7 2 8]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
arr=np.random.randint(10,size=(2,2,2,2))
Sum=np.sum(arr,axis=(2,3))
print(Sum)

[[21 12]
 [ 9 29]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [13]:
arr=np.array([1,2,3,4,5,6])
subsets=int(input("enter number of subset you want to create for the array: "))
arr2=np.split(arr,subsets)
subset_vector=np.array([])
for i in range(len(arr2)):
  j=0
  while j<arr2[i].size:
    subset_vector=np.append(subset_vector,i)
    j+=1
subset_vector

enter number of subset you want to create for the array: 2


array([0., 0., 0., 1., 1., 1.])

\#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
np.random.seed(11)
arr1=np.random.randint(10,size=(3,3))
arr2=np.random.randint(10,size=(3,4))
product_=np.dot(arr1,arr2)
print(product_)
for i in range(product_.shape[0]):
  print(product_[i][i])

[[ 1 44 26 10]
 [12 89 77 18]
 [40 48 60 34]]
1
89
60


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
v = np.array([1, 2, 3, 4, 5])
result = np.zeros(len(v) * (3 + 1), dtype=int)

result[::3 + 1] = v

print(result)


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(5,5,3))
arr2=np.random.randint(10,size=(5,5))

for i in range(arr.ndim):
  print(np.dot(arr[:,:,i],arr2))


[[ 87 118  59 105 127]
 [100 141  85 141 183]
 [ 96 134  84 124 166]
 [ 36  76  86  66  82]
 [ 34  87  93  73  76]]
[[ 31  77  85  78  77]
 [ 80 124  82 120 150]
 [ 48 106 108  94  81]
 [ 75 106  69  99 125]
 [ 60  78  34  80  75]]
[[ 51  72  49  71 119]
 [ 39  50  27  73  89]
 [ 81 130  90 107 129]
 [ 83 136 106 111 147]
 [ 88 142 104 152 149]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(3,3))
print("the original array: ","\n",arr)
i1=int(input("please enter number between the 0-2: "))
i2=int(input("please enter another number between the 0-2: "))
temp=np.copy(arr[i1,:])
arr[i1,:]=arr[i2,:]
arr[i2,:]=temp
print("array after swaping two raws: ","\n",arr)

the original array:  
 [[9 0 1]
 [7 1 7]
 [2 8 0]]
please enter number between the 0-2: 0
please enter another number between the 0-2: 2
array after swaping two raws:  
 [[2 8 0]
 [7 1 7]
 [9 0 1]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C=np.array([1,2,1,0,2,4,0,3,4,3])
arr=np.array([])
for i in range(C.size):
  F=C[i]
  for j in range(F):
    arr=np.append(arr,i)

print(arr)

[0. 1. 1. 2. 4. 4. 5. 5. 5. 5. 7. 7. 7. 8. 8. 8. 8. 9. 9. 9.]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

arr = np.array([10, 20, 30, 40, 50, 60])
arr2 = sliding_window_view(arr, window_shape=3)
print(arr2)
Mean=arr2.mean(axis=1)
print(Mean)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]
[20. 30. 40. 50.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
arr=np.array([10,20,30,40,50,60])
arr2=np.zeros(shape=(arr.size-2,3))
for i in range(arr.size-2):
  j=0
  while j <3:
    arr2[i][j]=arr[j+i]
    j+=1
print(arr2)

[[10. 20. 30.]
 [20. 30. 40.]
 [30. 40. 50.]
 [40. 50. 60.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
arr = np.array([True, False, True])
np.logical_not(arr, out=arr)

print(arr)


[False  True False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
p0=np.array([[0,2],
            [2,1],
            [3,3]])
p1=np.array([[3,4],
             [5,3],
             [4,2]])
p=np.array([3,1])
dist_arr=np.array([])
for i in range(len(p0)):
  diff1=p-p0[i]
  diff2=p-p1[i]
  dist1=np.sqrt(np.sum(diff1**2))
  dist2=np.sqrt(np.sum(diff2**2))
  if(dist1>dist2):
    dist_arr=np.append(dist_arr,(dist1,dist2))
  else:
    dist_arr=np.append(dist_arr,(dist2,dist1))
print(dist_arr)

[3.16227766 3.         2.82842712 1.         2.         1.41421356]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [3]:
def extract_centered_subarray(arr, center, shape, fill=0):
    arr = np.asarray(arr)
    output = np.full(shape, fill, dtype=arr.dtype)

    center = np.asarray(center)
    shape = np.asarray(shape)

    start = center - shape // 2
    end = start + shape


    src_start = np.maximum(start, 0)
    src_end = np.minimum(end, arr.shape)

    dst_start = src_start - start
    dst_end = dst_start + (src_end - src_start)


    output[tuple(slice(ds, de) for ds, de in zip(dst_start, dst_end))] = \
        arr[tuple(slice(ss, se) for ss, se in zip(src_start, src_end))]

    return output


arr = np.arange(1, 10).reshape(3, 3)
result = extract_centered_subarray(arr, center=(0, 0), shape=(3, 3), fill=0)
print(result)

[[0 0 0]
 [0 1 2]
 [0 4 5]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr2=np.zeros(shape=(arr.size-3,4))
for i in range(arr.size-3):
  j=0
  while j <4:
    arr2[i][j]=arr[j+i]
    j+=1
print(arr2)

[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]
 [ 4.  5.  6.  7.]
 [ 5.  6.  7.  8.]
 [ 6.  7.  8.  9.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10. 11.]
 [ 9. 10. 11. 12.]
 [10. 11. 12. 13.]
 [11. 12. 13. 14.]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix_a)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [ ]:
arr=np.array([1,2,6,1,7,4,6,8,7,1,7,9])
Mode=np.bincount(arr)
print(Mode.argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [6]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view


np.random.seed(0)
arr = np.random.rand(10, 10)

blocks = sliding_window_view(arr, (3, 3))

print("Shape of blocks array:", blocks.shape)
print("\nFirst 3x3 block:\n", blocks[0, 0])


Shape of blocks array: (8, 8, 3, 3)

First 3x3 block:
 [[0.5488135  0.71518937 0.60276338]
 [0.79172504 0.52889492 0.56804456]
 [0.97861834 0.79915856 0.46147936]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [7]:
import numpy as np

p, n = 5, 4


A = np.random.rand(p, n, n)

X = np.random.rand(p, n, 1)


result = np.matmul(A, X).sum(axis=0)


print("Shape of result:", result.shape)
print("Result:\n", result)


Shape of result: (4, 1)
Result:
 [[5.7456331 ]
 [5.11012552]
 [4.39108648]
 [5.17038472]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(16,16))
arr=arr.reshape(4,4,4,4)
Sum=arr.sum(axis=(2,3))
print(Sum)

[[59 71 71 61]
 [68 67 64 53]
 [62 75 94 35]
 [86 67 66 71]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(30,size=10)

arr2=np.sort(np.copy(arr))[::-1]
n=int(input("enter the n to find n largest number: "))
print(arr)
print("the n largest number is :",arr2[n-1])

enter the n to find n largest number: 3
[25 16 27 17 23 13 12  1  7 18]
the n largest number is : 23


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
arr1=np.array([1,2])
arr2=np.array(["a","b"])
arr3=np.array([True,False])
X, Y, Z = np.meshgrid(arr1, arr2, arr3)
cartesian_product = np.array([X.ravel(), Y.ravel(), Z.ravel()]).T
cartesian_product

array([['1', 'a', 'True'],
       ['1', 'a', 'False'],
       ['2', 'a', 'True'],
       ['2', 'a', 'False'],
       ['1', 'b', 'True'],
       ['1', 'b', 'False'],
       ['2', 'b', 'True'],
       ['2', 'b', 'False']], dtype='<U21')

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
color_dtype=np.dtype([
    ("red",'uint8'),
    ("green",'uint8'),
    ("blue",'uint8'),
    ("alpha",'uint8')
])
first_color=np.array([(50,100,40,30),(30,120,70,47)],dtype=color_dtype)
print(first_color)
print(first_color.dtype)
print("access the red values:",first_color["red"])

[(50, 100, 40, 30) (30, 120, 70, 47)]
[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]
[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]
access the red values [50 30]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
#method 1
np.random.seed(11)
arr=np.random.randint(10,size=5)
print(arr**3)
#method 2
print(arr*arr*arr)
#method 3
print(np.power(arr,3))

[729   0   1 343   1]
[729   0   1 343   1]
[729   0   1 343   1]



#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(20,size=(8,3))
arr2=np.array([[4,2],[3,6]])
for i in range (len(arr)):
  if(np.intersect1d(arr[i,:],arr2[0,:]).size==2 or np.intersect1d(arr[i,:],arr2[1,:]).size==2 ):
      print(arr[i,:])

[ 4  2 12]
[ 3  6 11]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
arr=np.array([[2,2,3],[1,1,1],[7,7,7],[4,2,1],[1,8,3],[1,1,1],[9,9,9],[1,1,1],[1,1,1],[1,1,1]])
arr2=np.array([])
for i in range(len(arr)):
  temp=arr[i,:]
  if(~(temp[0]==temp[1] and temp[0]==temp[2])):
    arr2=np.append(arr2,temp)
arr2.reshape(-1,3)

array([[2., 2., 3.],
       [4., 2., 1.],
       [1., 8., 3.]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
arr=np.array([3,5,8,11])
bin_repr=np.binary_repr(arr[0], width=None)


1


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
arr=np.array([[2,2,3],[1,1,1],[7,7,7],[4,2,1],[1,8,3],[1,1,1],[9,9,9],[1,1,1],[1,1,1],[1,1,1]])
np.unique(arr,axis=0)

array([[1, 1, 1],
       [1, 8, 3],
       [2, 2, 3],
       [4, 2, 1],
       [7, 7, 7],
       [9, 9, 9]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
np.random.seed(11)
A=np.random.randint(10,size=5)
print("vector A","\n",A)
B=np.random.randint(10,size=5)
print("vector B","\n",B)
print("----------------------")
print("the outer product:","\n",np.einsum('i,j->ij', A, B))
print("the sum: ","\n",np.einsum('n,n', A,B))
print("the multiply: ","\n",np.einsum('i,i->i', A,B))
print("the inner product: ","\n",np.einsum('i,i->', A,B))

vector A 
 [9 0 1 7 1]
vector B 
 [7 2 8 0 0]
----------------------
the outer product: 
 [[63 18 72  0  0]
 [ 0  0  0  0  0]
 [ 7  2  8  0  0]
 [49 14 56  0  0]
 [ 7  2  8  0  0]]
the sum:  
 71
the multiply:  
 [63  0  8  0  0]
the inner product:  
 71


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [2]:
import numpy as np


X = np.array([0, 1, 3, 6, 10])
Y = np.array([0, 2, 1, 5, 4])


dx = np.diff(X)
dy = np.diff(Y)
segment_lengths = np.sqrt(dx**2 + dy**2)
cumulative_lengths = np.insert(np.cumsum(segment_lengths), 0, 0)


num_points = 100
uniform_distances = np.linspace(0, cumulative_lengths[-1], num_points)

new_X = np.interp(uniform_distances, cumulative_lengths, X)
new_Y = np.interp(uniform_distances, cumulative_lengths, Y)

print(new_X)
print(new_Y)

[ 0.          0.06141391  0.12282782  0.18424172  0.24565563  0.30706954
  0.36848345  0.42989735  0.49131126  0.55272517  0.61413908  0.67555299
  0.73696689  0.7983808   0.85979471  0.92120862  0.98262252  1.08807286
  1.21090068  1.3337285   1.45655631  1.57938413  1.70221194  1.82503976
  1.94786757  2.07069539  2.1935232   2.31635102  2.43917883  2.56200665
  2.68483447  2.80766228  2.9304901   3.03576674  3.11816215  3.20055755
  3.28295295  3.36534836  3.44774376  3.53013916  3.61253457  3.69492997
  3.77732537  3.85972078  3.94211618  4.02451159  4.10690699  4.18930239
  4.2716978   4.3540932   4.4364886   4.51888401  4.60127941  4.68367481
  4.76607022  4.84846562  4.93086102  5.01325643  5.09565183  5.17804723
  5.26044264  5.34283804  5.42523345  5.50762885  5.59002425  5.67241966
  5.75481506  5.83721046  5.91960587  6.00323586  6.13646133  6.2696868
  6.40291228  6.53613775  6.66936322  6.80258869  6.93581416  7.06903963
  7.2022651   7.33549057  7.46871605  7.60194152  7.

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
np.random.seed(11)
arr=np.random.randint(10,size=(6,3))
n=10
arr2=np.array([])
for i in range(len(arr)):
  temp=arr[i,:]
  if np.sum(temp)==n:
    arr2=np.append(arr2,temp)
print(arr)
print(arr2.reshape(-1,3))

[[9 0 1]
 [7 1 7]
 [2 8 0]
 [0 4 2]
 [1 5 5]
 [7 4 1]]
[[9. 0. 1.]
 [2. 8. 0.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
arr=np.random.randint(100,size=10)
Mean=np.array([])
for i in range(50):
  ind=np.random.choice(arr.size,size=4)
  arr2=np.copy(arr[ind])
  Mean=np.append(Mean,arr2.mean())
ci_lower = np.percentile(Mean, 2.5)
ci_upper = np.percentile(Mean, 97.5)

print("95% Confidence Interval for the Mean:", (ci_lower, ci_upper))

95% Confidence Interval for the Mean: (np.float64(25.80625), np.float64(64.99374999999999))
